### ISSUE TITLE
[ kakfa ] Missing dependency

### ISSUE THREAD

**Issue by jucaf** [keedio/buildoopRecipes#74]
confirmed version 0.8.0
When service start raises a warning alerting missing dependency mx4j-tools, packae mx4j should be included as dependency and created symbolic link /usr/share/java/mx4j/mx4j-tools.jar--> /usr/lib/kafka/libs/mx4j-tools.jar

**Comment by rolmovel** [comment]
This library is optional. Needed in case you want to access JMX via HTTP.
