### ISSUE TITLE
[ spark 1.2 ] Missing symbolic links

### ISSUE THREAD

**Issue by jucaf** [keedio/buildoopRecipes#78]
RPM should create symbolic links: 
/usr/lib/spark/default -->/ usr/lib/spark/spark-1.3.1-bin-2.2.0
/usr/lib/spark/spark-1.3.1-bin-2.2.0/conf --> /etc/spark/conf

**Comment by alcuma** [comment]
Symbolic links have been created
The conf directories are

/etc/spark/conf -> /etc/spark/conf.dist
/etc/spark/conf.dist -> /usr/lib/spark/default/conf
